// Copyright © 2023 - 2026 Static Site Generator (SSG). All rights reserved.
// SPDX-License-Identifier: Apache-2.0 OR MIT

#![allow(clippy::unwrap_used, clippy::expect_used)]

//! Regression tests for issue #537 — YAML frontmatter is parsed by a
//! real YAML parser, not the previous hand-rolled split-on-colon
//! scanner that stored every value as a string and dropped lists and
//! nested maps.

use ssg_core::parse_frontmatter;

#[test]
fn yaml_frontmatter_indent_list_is_parsed() {
    let input = "---\ntags:\n  - welcome\n  - getting-started\n---\n# Body\n";
    let (fm, body) = parse_frontmatter(input);

    let tags = fm
        .get("tags")
        .and_then(|v| v.as_array())
        .expect("tags should be a YAML sequence, not a string");
    assert_eq!(tags.len(), 2);
    assert_eq!(tags[0].as_str(), Some("welcome"));
    assert_eq!(tags[1].as_str(), Some("getting-started"));
    assert!(body.contains("# Body"));
}

#[test]
fn yaml_frontmatter_flow_list_is_parsed() {
    let input = "---\ntags: [rust, wasm, ssg]\n---\nbody\n";
    let (fm, _body) = parse_frontmatter(input);

    let tags = fm
        .get("tags")
        .and_then(|v| v.as_array())
        .expect("flow list should parse to a YAML sequence");
    assert_eq!(tags.len(), 3);
    assert_eq!(tags[2].as_str(), Some("ssg"));
}

#[test]
fn yaml_frontmatter_nested_map_is_parsed() {
    let input =
        "---\nauthor:\n  name: Jane\n  email: jane@example.com\n---\nbody\n";
    let (fm, _body) = parse_frontmatter(input);

    let author = fm
        .get("author")
        .and_then(|v| v.as_object())
        .expect("author should be a nested mapping");
    assert_eq!(author.get("name").and_then(|v| v.as_str()), Some("Jane"));
    assert_eq!(
        author.get("email").and_then(|v| v.as_str()),
        Some("jane@example.com")
    );
}

#[test]
fn yaml_frontmatter_simple_key_value_still_works() {
    // Backward-compat sanity: the previous parser handled these.
    let input =
        "---\ntitle: Hello\ndate: 2026-01-01\nlayout: post\n---\n# Body\n";
    let (fm, body) = parse_frontmatter(input);

    assert_eq!(fm.get("title").and_then(|v| v.as_str()), Some("Hello"));
    assert_eq!(fm.get("layout").and_then(|v| v.as_str()), Some("post"));
    // `date: 2026-01-01` is parsed as a YAML date by serde_yaml_ng; in
    // round-trip through serde_json::Value it surfaces as a string.
    assert!(fm.contains_key("date"));
    assert!(body.contains("# Body"));
}

#[test]
fn yaml_frontmatter_scaffold_first_post_shape() {
    // Mirrors the exact frontmatter shape that
    // `ssg new` writes to `content/blog/first-post.md` — the
    // regression that motivated this fix (#537). The previous parser
    // could not extract `tags` as a list, so `tags/welcome/index.html`
    // was never generated by the downstream tag pipeline.
    let input = "---\ntitle: First Post\ndescription: My first blog post\nlayout: post\ndate: 2026-01-01\nauthor: Acme Team\ntags:\n  - welcome\n  - getting-started\ncategories:\n  - blog\n---\n\n# First Post\n";
    let (fm, body) = parse_frontmatter(input);

    let tags = fm
        .get("tags")
        .and_then(|v| v.as_array())
        .expect("scaffold tags should parse as a sequence");
    let collected: Vec<&str> = tags.iter().filter_map(|v| v.as_str()).collect();
    assert_eq!(collected, vec!["welcome", "getting-started"]);

    let categories = fm
        .get("categories")
        .and_then(|v| v.as_array())
        .expect("scaffold categories should parse as a sequence");
    assert_eq!(categories.len(), 1);
    assert_eq!(categories[0].as_str(), Some("blog"));

    assert!(body.contains("# First Post"));
}

#[test]
fn yaml_frontmatter_malformed_returns_empty_map() {
    let input = "---\ntags: [unclosed\n---\nbody\n";
    let (fm, body) = parse_frontmatter(input);
    assert!(fm.is_empty());
    assert!(body.contains("body"));
}
