// Copyright © 2023 - 2026 Static Site Generator (SSG). All rights reserved.
// SPDX-License-Identifier: Apache-2.0 OR MIT

#![cfg_attr(test, allow(clippy::unwrap_used, clippy::expect_used))]
//! # ssg-rpc — Edge RPC for SSG
//!
//! Tracking issue: [#548] — `feat(edge): Edge RPC — JSON-over-POST
//! with shared TS schema`.
//!
//! ## What this crate gives you
//!
//! * A `#[ssg_rpc]` proc-macro you stick on a free function.
//! * A static dispatch table that maps the function's name to a JSON
//!   trampoline (`String` → `Result<String, RpcError>`).
//! * A schema producer that emits TypeScript declarations into
//!   `dist/.ssg/rpc.d.ts` at build time so the matching JS client is
//!   fully typed end-to-end.
//!
//! ## Wire format
//!
//! Each registered RPC is reachable at `POST /__rpc/<fn_name>`. The
//! body is the JSON-encoded `Input`. Responses are:
//!
//! | Status | Body                                  | When                       |
//! |--------|---------------------------------------|----------------------------|
//! | 200    | JSON-encoded `Output`                 | `Result::Ok`               |
//! | 400    | `{"error": "..."}` (bad request)      | malformed payload          |
//! | 404    | `{"error": "unknown rpc"}`            | unknown name (no leak)     |
//! | 405    | `{"error": "method not allowed"}`     | non-POST verb              |
//! | 500    | `{"error": "..."}`                    | handler returned `Err`     |
//!
//! ## Locked-in design decisions
//!
//! * **JSON, not tRPC**. The 2-3 KB tRPC runtime is too heavy for an
//!   edge-static target — we ship `web/rpc.js` at < 1 KB minified.
//! * **POST only**. GET would invite CDN caching surprises.
//! * **Unauthenticated by default**. Authentication is the user's
//!   responsibility via a middleware layer they wrap around the
//!   dispatcher (see `RpcError::Unauthorized` for the canonical
//!   shape).
//!
//! [#548]: https://github.com/sebastienrousseau/static-site-generator/issues/548

#![deny(missing_docs)]

pub mod dispatch;
pub mod schema;
pub mod ts;

pub use dispatch::{
    dispatch, registered_names, RpcDescriptor, RpcDescriptorRef,
};
pub use schema::{schema_for, schema_for_result, RpcSchema, SchemaValue};
pub use ts::{emit_typescript, emit_typescript_for, EmitOptions};

// Re-export `inventory` so the proc-macro can reference it via the
// `ssg_rpc::inventory` path without users needing to add the crate
// to their own Cargo.toml.
pub use inventory;

/// The attribute macro that registers a function with the RPC
/// dispatch table.
pub use ssg_rpc_macro::ssg_rpc;

use thiserror::Error;

/// Canonical error type returned by every `#[ssg_rpc]` function.
///
/// The variant names are deliberately stable — the JSON dispatcher
/// uses them to choose an HTTP status code, so renaming would be a
/// wire-protocol break.
///
/// # Examples
///
/// ```
/// use ssg_rpc::RpcError;
///
/// let err = RpcError::BadRequest("missing field".into());
/// assert_eq!(err.to_string(), "bad request: missing field");
/// assert_eq!(err.status_code(), 400);
/// ```
#[derive(Debug, Error)]
pub enum RpcError {
    /// Malformed input payload (HTTP 400). Includes the parser error
    /// for developer ergonomics; do not leak this to untrusted users
    /// without sanitising first.
    #[error("bad request: {0}")]
    BadRequest(String),

    /// Caller is not allowed (HTTP 401). Generated by user-provided
    /// middleware; the dispatcher itself is unauthenticated.
    #[error("unauthorized")]
    Unauthorized,

    /// Resource not found in the handler (HTTP 404). Distinct from
    /// "unknown RPC name", which is generated by the dispatcher
    /// itself.
    #[error("not found")]
    NotFound,

    /// Generic 5xx — handler is broken.
    #[error("internal error: {0}")]
    Internal(String),
}

impl RpcError {
    /// Maps the error to the HTTP status the dispatcher should
    /// return. The choice of integer (vs `http::StatusCode`) keeps
    /// this crate dependency-free for WASM targets that can't link
    /// the `http` crate at runtime.
    ///
    /// # Examples
    ///
    /// ```
    /// use ssg_rpc::RpcError;
    ///
    /// assert_eq!(RpcError::BadRequest("x".into()).status_code(), 400);
    /// assert_eq!(RpcError::Unauthorized.status_code(), 401);
    /// assert_eq!(RpcError::NotFound.status_code(), 404);
    /// assert_eq!(RpcError::Internal("boom".into()).status_code(), 500);
    /// ```
    #[must_use]
    pub const fn status_code(&self) -> u16 {
        match self {
            Self::BadRequest(_) => 400,
            Self::Unauthorized => 401,
            Self::NotFound => 404,
            Self::Internal(_) => 500,
        }
    }

    /// Serialises to the standard `{"error": "..."}` wire body that
    /// the JS client knows how to surface.
    ///
    /// # Examples
    ///
    /// ```
    /// use ssg_rpc::RpcError;
    ///
    /// let body = RpcError::NotFound.to_wire_body();
    /// assert_eq!(body, r#"{"error":"not found"}"#);
    ///
    /// // Quotes and backslashes in the message are escaped so the
    /// // output is always valid JSON.
    /// let tricky = RpcError::BadRequest(r#"oops "x" \n"#.into());
    /// let v: serde_json::Value =
    ///     serde_json::from_str(&tricky.to_wire_body()).unwrap();
    /// assert_eq!(v["error"], r#"bad request: oops "x" \n"#);
    /// ```
    #[must_use]
    pub fn to_wire_body(&self) -> String {
        // Hand-rolled to avoid pulling a full `serde_json::to_string`
        // round-trip for a one-field object — also guarantees we
        // never emit an unbalanced brace on a serialisation failure.
        let msg = self.to_string();
        let escaped = msg.replace('\\', "\\\\").replace('"', "\\\"");
        format!("{{\"error\":\"{escaped}\"}}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn status_codes_are_stable() {
        assert_eq!(RpcError::BadRequest("x".into()).status_code(), 400);
        assert_eq!(RpcError::Unauthorized.status_code(), 401);
        assert_eq!(RpcError::NotFound.status_code(), 404);
        assert_eq!(RpcError::Internal("x".into()).status_code(), 500);
    }

    #[test]
    fn wire_body_escapes_quotes_and_backslashes() {
        let err = RpcError::BadRequest(r#"oops "quoted" \n"#.into());
        let body = err.to_wire_body();
        assert!(body.starts_with("{\"error\":\""));
        assert!(body.ends_with("\"}"));
        assert!(body.contains(r#"\""#));
        assert!(body.contains(r"\\"));
    }

    #[test]
    fn wire_body_is_round_trippable_json() {
        let err = RpcError::Internal("boom".into());
        let body = err.to_wire_body();
        let parsed: serde_json::Value = serde_json::from_str(&body).unwrap();
        assert_eq!(parsed["error"], "internal error: boom");
    }

    #[test]
    fn error_display_messages_are_stable() {
        // Display strings are part of the on-the-wire body — renaming
        // would silently break JS clients that pattern-match them.
        assert_eq!(
            RpcError::BadRequest("nope".into()).to_string(),
            "bad request: nope"
        );
        assert_eq!(RpcError::Unauthorized.to_string(), "unauthorized");
        assert_eq!(RpcError::NotFound.to_string(), "not found");
        assert_eq!(
            RpcError::Internal("boom".into()).to_string(),
            "internal error: boom"
        );
    }

    #[test]
    fn wire_body_for_unauthorized_is_valid_json() {
        let body = RpcError::Unauthorized.to_wire_body();
        let v: serde_json::Value = serde_json::from_str(&body).unwrap();
        assert_eq!(v["error"], "unauthorized");
    }

    #[test]
    fn wire_body_for_not_found_is_valid_json() {
        let body = RpcError::NotFound.to_wire_body();
        let v: serde_json::Value = serde_json::from_str(&body).unwrap();
        assert_eq!(v["error"], "not found");
    }

    #[test]
    fn wire_body_handles_no_special_chars() {
        let err = RpcError::Internal("simple".into());
        let body = err.to_wire_body();
        assert_eq!(body, r#"{"error":"internal error: simple"}"#);
    }

    #[test]
    fn status_code_is_const_callable() {
        // Compile-time evidence the method is `const fn` — if it
        // weren't, this binding would not type-check.
        const CODE: u16 = RpcError::Unauthorized.status_code();
        assert_eq!(CODE, 401);
    }
}
