// Copyright © 2023 - 2026 Static Site Generator (SSG). All rights reserved.
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! TypeScript emitter — JSON Schema → `.d.ts`.
//!
//! Why hand-rolled? The `json-schema-to-typescript` ecosystem is
//! Node-only; the alternative crate `typescript-type-def` only
//! understands its own native types (no JSON Schema input). We need
//! the smallest possible Rust → TS translation for a tightly-scoped
//! schema vocabulary (the subset emitted by schemars 1.x for plain
//! `#[derive(JsonSchema)]` structs and enums).
//!
//! Supported schema features (sufficient for >95% of RPC payloads):
//!
//! * Primitives: string, number, integer, boolean, null
//! * Arrays (with item type)
//! * Object with `properties` + `required`
//! * `enum` of literal strings
//! * `anyOf` / `oneOf` → TS union
//! * `$ref` → reference into the local `$defs` table
//!
//! Everything else falls through to `unknown` rather than panicking —
//! the user always gets a working `.d.ts`, even if it loses some
//! precision.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use serde_json::Value;

use crate::dispatch::iter_descriptors;
use crate::schema::RpcSchema;

/// Options for the `.d.ts` emitter.
///
/// # Examples
///
/// ```
/// use ssg_rpc::EmitOptions;
///
/// // Default options include an AUTO-GENERATED banner and enable
/// // the `Rpc` index interface.
/// let opts = EmitOptions::default();
/// assert!(opts.header.contains("AUTO-GENERATED"));
/// assert!(opts.emit_rpc_index);
///
/// // Customise the header (useful for embedding a schema hash) or
/// // disable the index interface entirely.
/// let custom = EmitOptions {
///     header: String::from("// my-app rpc bindings\n"),
///     emit_rpc_index: false,
/// };
/// assert_eq!(custom.header, "// my-app rpc bindings\n");
/// assert!(!custom.emit_rpc_index);
/// ```
#[derive(Clone, Debug)]
pub struct EmitOptions {
    /// Header comment placed at the top of the file. Useful for
    /// embedding the schema hash so CI can diff it.
    pub header: String,
    /// Whether to emit the `Rpc` wrapper type collecting every
    /// function's signature. Defaults to `true`.
    pub emit_rpc_index: bool,
}

impl Default for EmitOptions {
    /// Returns options producing the canonical `.d.ts` shape: an
    /// `AUTO-GENERATED` banner plus the `Rpc` index interface.
    ///
    /// # Examples
    ///
    /// ```
    /// use ssg_rpc::EmitOptions;
    ///
    /// let opts = EmitOptions::default();
    /// assert!(opts.header.starts_with("// AUTO-GENERATED by ssg-rpc"));
    /// assert!(opts.emit_rpc_index);
    /// ```
    fn default() -> Self {
        Self {
            header: String::from(
                "// AUTO-GENERATED by ssg-rpc. Do not edit by hand.\n\
                 // Run `cargo build` after touching the matching\n\
                 // Rust types to regenerate.\n",
            ),
            emit_rpc_index: true,
        }
    }
}

/// Emit a TypeScript declaration file for every registered RPC.
///
/// Each RPC becomes a TS function signature on the `Rpc` interface:
///
/// ```ts
/// export interface Rpc {
///   like_post(input: LikeInput): Promise<LikeOutput>;
/// }
/// ```
///
/// Input and output types are emitted as named interfaces (or type
/// aliases for primitives), nominally `<FnName>Input` /
/// `<FnName>Output`.
///
/// # Examples
///
/// ```
/// use ssg_rpc::{emit_typescript, EmitOptions};
///
/// // Walks the global inventory of `#[ssg_rpc]` functions. With
/// // default options the file always starts with the AUTO-GENERATED
/// // banner — even if no RPC has been registered in this binary.
/// let ts = emit_typescript(&EmitOptions::default());
/// assert!(ts.starts_with("// AUTO-GENERATED by ssg-rpc"));
/// ```
#[must_use]
pub fn emit_typescript(opts: &EmitOptions) -> String {
    let mut schemas: Vec<RpcSchema> =
        iter_descriptors().map(|d| (d.schema)()).collect();
    schemas.sort_by(|a, b| a.name.cmp(b.name));
    emit_typescript_for(&schemas, opts)
}

/// Variant of [`emit_typescript`] that takes an explicit schema set,
/// useful in tests where we don't want to depend on the global
/// inventory.
///
/// # Examples
///
/// ```
/// use ssg_rpc::{emit_typescript_for, EmitOptions};
/// use ssg_rpc::schema::RpcSchema;
/// use serde_json::json;
///
/// let s = RpcSchema {
///     name: "greet",
///     input: json!({"type": "string"}),
///     output: json!({"type": "string"}),
/// };
/// let opts = EmitOptions {
///     header: String::new(),
///     emit_rpc_index: true,
/// };
/// let out = emit_typescript_for(&[s], &opts);
///
/// // Primitive inputs become type aliases; the `Rpc` index lists
/// // every function we passed in.
/// assert!(out.contains("export type GreetInput = string;"));
/// assert!(out.contains("export type GreetOutput = string;"));
/// assert!(out.contains(
///     "greet(input: GreetInput): Promise<GreetOutput>;"
/// ));
/// ```
#[must_use]
pub fn emit_typescript_for(
    schemas: &[RpcSchema],
    opts: &EmitOptions,
) -> String {
    let mut out = String::with_capacity(4096);
    out.push_str(&opts.header);
    out.push('\n');

    // First pass — every named definition (one Input + one Output per
    // RPC) collected so we can resolve refs.
    for s in schemas {
        let input_name = type_name_for(&s.input, s.name, "Input");
        let output_name = type_name_for(&s.output, s.name, "Output");
        emit_named_type(&input_name, &s.input, &mut out);
        emit_named_type(&output_name, &s.output, &mut out);
    }

    if opts.emit_rpc_index {
        out.push_str("export interface Rpc {\n");
        for s in schemas {
            let input_name = type_name_for(&s.input, s.name, "Input");
            let output_name = type_name_for(&s.output, s.name, "Output");
            let _ = writeln!(
                out,
                "  {fn_name}(input: {input_name}): Promise<{output_name}>;",
                fn_name = s.name,
            );
        }
        out.push_str("}\n");
    }

    out
}

/// Pick the TS interface name for a schema, preferring the schema's
/// own `title` field when present. This keeps the `.d.ts` interfaces
/// aligned with the schemars-emitted JSON Schema titles (which match
/// the Rust struct names), so site authors don't see `LikeInput` in
/// the schema and `LikePostInput` in the generated `.d.ts`.
fn type_name_for(schema: &Value, fn_name: &str, suffix: &str) -> String {
    schema
        .get("title")
        .and_then(Value::as_str)
        .filter(|t| !t.is_empty() && is_valid_ts_identifier(t))
        .map_or_else(|| type_name(fn_name, suffix), String::from)
}

fn is_valid_ts_identifier(s: &str) -> bool {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' || c == '$' => {}
        _ => return false,
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
}

fn type_name(fn_name: &str, suffix: &str) -> String {
    let mut head = String::new();
    let mut cap_next = true;
    for c in fn_name.chars() {
        if c == '_' {
            cap_next = true;
            continue;
        }
        if cap_next {
            head.extend(c.to_uppercase());
            cap_next = false;
        } else {
            head.push(c);
        }
    }
    format!("{head}{suffix}")
}

fn emit_named_type(name: &str, schema: &Value, out: &mut String) {
    // If the schema is an object with properties, emit an interface.
    // Otherwise emit a type alias.
    let schema = unwrap_ref(schema, schema);

    if is_object_with_properties(schema) {
        let _ = writeln!(out, "export interface {name} {{");
        emit_object_body(schema, out, 2);
        out.push_str("}\n\n");
    } else {
        let ts = ts_type_for(schema, schema);
        let _ = writeln!(out, "export type {name} = {ts};\n");
    }
}

fn emit_object_body(schema: &Value, out: &mut String, indent: usize) {
    let pad = " ".repeat(indent);
    let required: Vec<&str> = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|arr| arr.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();

    if let Some(props) = schema.get("properties").and_then(Value::as_object) {
        // Sort properties for stable output across builds.
        let sorted: BTreeMap<&String, &Value> = props.iter().collect();
        for (key, value) in sorted {
            let opt = if required.contains(&key.as_str()) {
                ""
            } else {
                "?"
            };
            let ts = ts_type_for(value, schema);
            let _ = writeln!(out, "{pad}{key}{opt}: {ts};");
        }
    }
}

fn is_object_with_properties(schema: &Value) -> bool {
    schema
        .get("properties")
        .and_then(Value::as_object)
        .is_some_and(|m| !m.is_empty())
}

fn unwrap_ref<'a>(schema: &'a Value, root: &'a Value) -> &'a Value {
    if let Some(r) = schema.get("$ref").and_then(Value::as_str) {
        if let Some(name) = r.strip_prefix("#/$defs/") {
            if let Some(target) = root.get("$defs").and_then(|d| d.get(name)) {
                return target;
            }
        }
    }
    schema
}

#[allow(clippy::too_many_lines)]
fn ts_type_for(schema: &Value, root: &Value) -> String {
    let schema = unwrap_ref(schema, root);

    // Enum of literal strings → TS string union.
    if let Some(en) = schema.get("enum").and_then(Value::as_array) {
        let parts: Vec<String> = en
            .iter()
            .map(|v| match v {
                Value::String(s) => format!("\"{}\"", escape_ts(s)),
                Value::Number(n) => n.to_string(),
                Value::Bool(b) => b.to_string(),
                Value::Null => "null".into(),
                _ => "unknown".into(),
            })
            .collect();
        if !parts.is_empty() {
            return parts.join(" | ");
        }
    }

    // anyOf / oneOf → TS union.
    for key in ["anyOf", "oneOf"] {
        if let Some(arr) = schema.get(key).and_then(Value::as_array) {
            let parts: Vec<String> =
                arr.iter().map(|s| ts_type_for(s, root)).collect();
            if !parts.is_empty() {
                return parts.join(" | ");
            }
        }
    }

    // `type` keyword.
    match schema.get("type") {
        Some(Value::String(t)) => ts_for_primitive_type(t, schema, root),
        Some(Value::Array(arr)) => {
            // `type: ["string", "null"]` → TS union.
            let parts: Vec<String> = arr
                .iter()
                .filter_map(|v| v.as_str())
                .map(|t| ts_for_primitive_type(t, schema, root))
                .collect();
            if parts.is_empty() {
                "unknown".into()
            } else {
                parts.join(" | ")
            }
        }
        _ => {
            // Inline object with properties (no explicit `type`) is
            // common in schemars output.
            if is_object_with_properties(schema) {
                let mut inline = String::from("{ ");
                let required: Vec<&str> = schema
                    .get("required")
                    .and_then(Value::as_array)
                    .map(|arr| arr.iter().filter_map(Value::as_str).collect())
                    .unwrap_or_default();
                if let Some(props) =
                    schema.get("properties").and_then(Value::as_object)
                {
                    let sorted: BTreeMap<&String, &Value> =
                        props.iter().collect();
                    let mut first = true;
                    for (k, v) in sorted {
                        if !first {
                            inline.push_str("; ");
                        }
                        first = false;
                        let opt = if required.contains(&k.as_str()) {
                            ""
                        } else {
                            "?"
                        };
                        let _ = write!(
                            inline,
                            "{k}{opt}: {ty}",
                            ty = ts_type_for(v, root)
                        );
                    }
                }
                inline.push_str(" }");
                inline
            } else {
                "unknown".into()
            }
        }
    }
}

fn ts_for_primitive_type(t: &str, schema: &Value, root: &Value) -> String {
    match t {
        "string" => "string".into(),
        "number" | "integer" => "number".into(),
        "boolean" => "boolean".into(),
        "null" => "null".into(),
        "array" => {
            let items = schema.get("items").map_or_else(
                || String::from("unknown"),
                |v| ts_type_for(v, root),
            );
            format!("{items}[]")
        }
        "object" => {
            if is_object_with_properties(schema) {
                // Inline object literal.
                let mut inline = String::from("{ ");
                let required: Vec<&str> = schema
                    .get("required")
                    .and_then(Value::as_array)
                    .map(|arr| arr.iter().filter_map(Value::as_str).collect())
                    .unwrap_or_default();
                let props = schema.get("properties").and_then(Value::as_object);
                if let Some(props) = props {
                    let sorted: BTreeMap<&String, &Value> =
                        props.iter().collect();
                    let mut first = true;
                    for (k, v) in sorted {
                        if !first {
                            inline.push_str("; ");
                        }
                        first = false;
                        let opt = if required.contains(&k.as_str()) {
                            ""
                        } else {
                            "?"
                        };
                        let _ = write!(
                            inline,
                            "{k}{opt}: {ty}",
                            ty = ts_type_for(v, root)
                        );
                    }
                }
                inline.push_str(" }");
                inline
            } else {
                "Record<string, unknown>".into()
            }
        }
        _ => "unknown".into(),
    }
}

fn escape_ts(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;
    use serde_json::json;

    fn opts() -> EmitOptions {
        EmitOptions {
            header: String::new(),
            emit_rpc_index: true,
        }
    }

    fn schema(name: &'static str, input: Value, output: Value) -> RpcSchema {
        RpcSchema {
            name,
            input,
            output,
        }
    }

    #[test]
    fn primitive_string_input_emits_type_alias() {
        let s = schema(
            "greet",
            json!({"type": "string"}),
            json!({"type": "string"}),
        );
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains("export type GreetInput = string;"), "{out}");
        assert!(out.contains("export type GreetOutput = string;"), "{out}");
    }

    #[test]
    fn object_with_required_emits_interface() {
        let s = schema(
            "like_post",
            json!({
                "type": "object",
                "properties": {
                    "post_id": {"type": "string"}
                },
                "required": ["post_id"]
            }),
            json!({
                "type": "object",
                "properties": {
                    "likes": {"type": "integer"}
                },
                "required": ["likes"]
            }),
        );
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains("export interface LikePostInput"), "{out}");
        assert!(out.contains("post_id: string"), "{out}");
        assert!(out.contains("export interface LikePostOutput"), "{out}");
        assert!(out.contains("likes: number"), "{out}");
        assert!(
            out.contains(
                "like_post(input: LikePostInput): Promise<LikePostOutput>;"
            ),
            "{out}"
        );
    }

    #[test]
    fn optional_property_emits_question_mark() {
        let s = schema(
            "f",
            json!({
                "type": "object",
                "properties": {
                    "a": {"type": "string"},
                    "b": {"type": "string"}
                },
                "required": ["a"]
            }),
            json!({"type": "string"}),
        );
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains("a: string"), "{out}");
        assert!(out.contains("b?: string"), "{out}");
    }

    #[test]
    fn enum_emits_union() {
        let s = schema(
            "pick",
            json!({"enum": ["red", "blue"]}),
            json!({"type": "string"}),
        );
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains("\"red\" | \"blue\""), "{out}");
    }

    #[test]
    fn array_emits_brackets() {
        let s = schema(
            "list",
            json!({"type": "array", "items": {"type": "string"}}),
            json!({"type": "string"}),
        );
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains("string[]"), "{out}");
    }

    #[test]
    fn ref_resolves_into_defs() {
        let s = schema(
            "with_ref",
            json!({
                "$ref": "#/$defs/Nested",
                "$defs": {
                    "Nested": {
                        "type": "object",
                        "properties": { "n": {"type": "integer"} },
                        "required": ["n"]
                    }
                }
            }),
            json!({"type": "string"}),
        );
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains("n: number"), "{out}");
    }

    #[test]
    fn rpc_index_can_be_disabled() {
        let s =
            schema("x", json!({"type": "string"}), json!({"type": "string"}));
        let out = emit_typescript_for(
            &[s],
            &EmitOptions {
                header: String::new(),
                emit_rpc_index: false,
            },
        );
        assert!(!out.contains("export interface Rpc {"), "{out}");
    }

    #[test]
    fn any_of_emits_union() {
        let s = schema(
            "u",
            json!({"anyOf": [{"type": "string"}, {"type": "null"}]}),
            json!({"type": "string"}),
        );
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains("string | null"), "{out}");
    }

    #[test]
    fn type_array_emits_union() {
        let s = schema(
            "u2",
            json!({"type": ["string", "null"]}),
            json!({"type": "string"}),
        );
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains("string | null"), "{out}");
    }

    #[test]
    fn boolean_primitive_maps() {
        let s =
            schema("b", json!({"type": "boolean"}), json!({"type": "boolean"}));
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains("export type BInput = boolean;"), "{out}");
    }

    #[test]
    fn type_name_camel_cases_underscores() {
        assert_eq!(type_name("like_post", "Input"), "LikePostInput");
        assert_eq!(type_name("x", "Output"), "XOutput");
        assert_eq!(type_name("snake_case_name", "I"), "SnakeCaseNameI");
    }

    #[test]
    fn unknown_type_falls_back_to_unknown() {
        let s =
            schema("weird", json!({"type": "ufo"}), json!({"type": "string"}));
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains("WeirdInput = unknown"), "{out}");
    }

    #[test]
    fn header_is_prepended() {
        let s =
            schema("g", json!({"type": "string"}), json!({"type": "string"}));
        let opts = EmitOptions {
            header: String::from("// header line\n"),
            emit_rpc_index: false,
        };
        let out = emit_typescript_for(&[s], &opts);
        assert!(out.starts_with("// header line"), "{out}");
    }

    #[test]
    fn default_options_contain_auto_generated_marker() {
        let opts = EmitOptions::default();
        assert!(opts.header.contains("AUTO-GENERATED"));
        assert!(opts.emit_rpc_index);
    }

    #[test]
    fn one_of_emits_union() {
        let s = schema(
            "o",
            json!({"oneOf": [{"type": "integer"}, {"type": "boolean"}]}),
            json!({"type": "string"}),
        );
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains("number | boolean"), "{out}");
    }

    #[test]
    fn array_without_items_falls_back_to_unknown() {
        let s =
            schema("a", json!({"type": "array"}), json!({"type": "string"}));
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains("unknown[]"), "{out}");
    }

    #[test]
    fn integer_type_maps_to_number() {
        let s =
            schema("n", json!({"type": "integer"}), json!({"type": "string"}));
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains("export type NInput = number;"), "{out}");
    }

    #[test]
    fn null_type_maps_to_null() {
        let s = schema("z", json!({"type": "null"}), json!({"type": "string"}));
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains("export type ZInput = null;"), "{out}");
    }

    #[test]
    fn object_without_properties_maps_to_record() {
        let s =
            schema("r", json!({"type": "object"}), json!({"type": "string"}));
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains("Record<string, unknown>"), "{out}");
    }

    #[test]
    fn object_with_inline_properties_emits_interface() {
        // No explicit `type` keyword — schemars often omits it.
        let s = schema(
            "i",
            json!({
                "properties": {
                    "k": {"type": "string"}
                },
                "required": ["k"]
            }),
            json!({"type": "string"}),
        );
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains("export interface IInput"), "{out}");
        assert!(out.contains("k: string"), "{out}");
    }

    #[test]
    fn enum_with_number_literals_emits_union() {
        let s =
            schema("e", json!({"enum": [1, 2, 3]}), json!({"type": "string"}));
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains("1 | 2 | 3"), "{out}");
    }

    #[test]
    fn enum_with_bool_and_null_emits_union() {
        let s = schema(
            "e",
            json!({"enum": [true, false, null]}),
            json!({"type": "string"}),
        );
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains("true | false | null"), "{out}");
    }

    #[test]
    fn enum_with_strings_escapes_special_chars() {
        let s = schema(
            "e",
            json!({"enum": ["a\\b", "c\"d"]}),
            json!({"type": "string"}),
        );
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains(r#""a\\b""#), "{out}");
        assert!(out.contains(r#""c\"d""#), "{out}");
    }

    #[test]
    fn ref_without_matching_def_falls_back() {
        // Dangling $ref — emitter should not panic.
        let s = schema(
            "r",
            json!({"$ref": "#/$defs/Missing"}),
            json!({"type": "string"}),
        );
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains("export type RInput"), "{out}");
    }

    #[test]
    fn nested_array_of_objects() {
        let s = schema(
            "n",
            json!({
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": { "a": {"type": "integer"} },
                    "required": ["a"]
                }
            }),
            json!({"type": "string"}),
        );
        let out = emit_typescript_for(&[s], &opts());
        // Inline object literal inside array brackets.
        assert!(out.contains("a: number"), "{out}");
        assert!(out.contains("[]"), "{out}");
    }

    #[test]
    fn rpc_index_lists_every_function() {
        let s1 =
            schema("alpha", json!({"type":"string"}), json!({"type":"string"}));
        let s2 =
            schema("beta", json!({"type":"string"}), json!({"type":"string"}));
        let out = emit_typescript_for(&[s1, s2], &opts());
        assert!(
            out.contains("alpha(input: AlphaInput): Promise<AlphaOutput>;"),
            "{out}"
        );
        assert!(
            out.contains("beta(input: BetaInput): Promise<BetaOutput>;"),
            "{out}"
        );
    }

    #[test]
    fn emit_typescript_from_inventory_returns_non_empty() {
        // Uses the global inventory (the `echo` descriptor lives in
        // dispatch.rs tests but is also registered into the live
        // inventory).
        let out = emit_typescript(&opts());
        assert!(!out.is_empty());
    }

    #[test]
    fn options_clone_works() {
        let a = EmitOptions::default();
        let b = a.clone();
        assert_eq!(a.header, b.header);
        assert_eq!(a.emit_rpc_index, b.emit_rpc_index);
    }

    #[test]
    fn empty_enum_array_falls_through_to_type_keyword() {
        // An empty `enum` should NOT short-circuit — emitter should
        // continue to the `type` branch.
        let s = schema(
            "e",
            json!({"enum": [], "type": "string"}),
            json!({"type": "string"}),
        );
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains("EInput = string"), "{out}");
    }

    #[test]
    fn empty_any_of_falls_through() {
        let s = schema(
            "u",
            json!({"anyOf": [], "type": "string"}),
            json!({"type": "string"}),
        );
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains("UInput = string"), "{out}");
    }

    #[test]
    fn type_array_with_only_unknown_strings_falls_back_to_unknown() {
        let s = schema("u", json!({"type": []}), json!({"type": "string"}));
        let out = emit_typescript_for(&[s], &opts());
        assert!(out.contains("UInput = unknown"), "{out}");
    }
}
