//! # SSG Server
//!
//! `ssg-server` is a simple and efficient HTTP server for serving static websites generated by the Shokunin Static Site Generator (SSG). It handles HTTP requests and responses, manages server operations, and provides robust error handling.
//!
//! ## Modules
//! - [`server`]: Contains the core `Server` struct and logic for managing HTTP connections.
//! - [`request`]: Handles incoming HTTP requests, parsing and validation.
//! - [`response`]: Provides utilities for crafting HTTP responses.
//! - [`error`]: Defines errors related to the server's operation.
//!

/// The `server` module contains the core `Server` struct and associated methods for starting
/// and managing the HTTP server.
pub mod server;

/// The `request` module is responsible for parsing and validating incoming HTTP requests.
pub mod request;

/// The `response` module provides tools and utilities for crafting HTTP responses.
pub mod response;

/// The `error` module defines various errors that can occur during server operation, including
/// those related to connections and malformed requests.
pub mod error;

pub use error::ServerError;
pub use server::Server;
