// Copyright © 2023 - 2026 Static Site Generator (SSG). All rights reserved.
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Project scaffolding.
//!
//! Generates a complete starter project structure when `ssg --new`
//! is invoked, including content, templates, config, and static assets.

use anyhow::{Context, Result};
use std::{fs, path::Path};

/// Generates a new project with the given name in the current directory.
pub fn scaffold_project(name: &str) -> Result<()> {
    let cwd = std::env::current_dir()?;
    scaffold_project_at(name, &cwd)
}

/// Generates a new project at the given base directory.
pub fn scaffold_project_at(name: &str, base: &Path) -> Result<()> {
    let root = base.join(name);
    if root.exists() {
        anyhow::bail!("Directory '{name}' already exists");
    }

    // Create directory structure
    let dirs = [
        "",
        "content",
        "content/blog",
        "templates/tera",
        "static/css",
        "data",
    ];
    for dir in &dirs {
        fs::create_dir_all(root.join(dir))
            .with_context(|| format!("Failed to create {name}/{dir}"))?;
    }

    // config.toml
    fs::write(
        root.join("config.toml"),
        format!(
            r#"site_name = "{name}"
content_dir = "content"
output_dir = "public"
template_dir = "templates"
base_url = "http://127.0.0.1:8000"
site_title = "{name}"
site_description = "A site built with SSG"
language = "en-GB"
"#
        ),
    )?;

    // content/index.md
    fs::write(
        root.join("content/index.md"),
        format!(
            r"---
title: Welcome to {name}
description: A fast, accessible static site built with SSG
layout: index
---

# Welcome

This is your new SSG site. Edit `content/index.md` to get started.

## Features

- Tera templating with inheritance
- WCAG 2.1 AA accessibility by default
- JSON-LD structured data for SEO
- Syntax highlighting for code blocks
- Responsive image optimisation
- Client-side search
"
        ),
    )?;

    // content/about.md
    fs::write(
        root.join("content/about.md"),
        r"---
title: About
description: About this site
layout: page
---

# About

This page was generated by [SSG](https://shokunin.one).
",
    )?;

    // content/blog/first-post.md
    fs::write(
        root.join("content/blog/first-post.md"),
        format!(
            r#"---
title: First Post
description: My first blog post
layout: post
date: 2026-01-01
author: {name} Team
tags:
  - welcome
  - getting-started
categories:
  - blog
---

# First Post

Welcome to **{name}**! This is your first blog post.

## Code Example

```rust
fn main() {{
    println!("Hello from {name}!");
}}
```

{{{{< tip >}}}}
Edit this file at `content/blog/first-post.md`.
{{{{< /tip >}}}}
"#
        ),
    )?;

    // templates/tera/base.html
    fs::write(
        root.join("templates/tera/base.html"),
        r##"<!DOCTYPE html>
<html lang="{{ site.language | default(value='en') }}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{{ page.title | default(value="Untitled") }}{% if site.title %} — {{ site.title }}{% endif %}{% endblock %}</title>
  {% if page.description %}<meta name="description" content="{{ page.description }}">{% endif %}
  <link rel="stylesheet" href="/css/style.css">
  {% block head_extra %}{% endblock %}
</head>
<body>
  <a href="#main-content" class="sr-only">Skip to main content</a>
  <header role="banner">
    <nav aria-label="Main navigation">
      <a href="/">{{ site.name | default(value="Home") }}</a>
      <a href="/about.html">About</a>
    </nav>
  </header>
  <main id="main-content" role="main">
    {% block content %}{% endblock %}
  </main>
  <footer role="contentinfo">
    <p>&copy; {{ site.name | default(value="") }}. Built with <a href="https://shokunin.one">SSG</a>.</p>
  </footer>
</body>
</html>
"##,
    )?;

    // templates/tera/page.html
    fs::write(
        root.join("templates/tera/page.html"),
        r#"{% extends "base.html" %}
{% block content %}{{ page.content | safe }}{% endblock %}
"#,
    )?;

    // templates/tera/post.html
    fs::write(
        root.join("templates/tera/post.html"),
        r#"{% extends "base.html" %}
{% block content %}
<article>
  <header>
    <h1>{{ page.title | default(value="") }}</h1>
    {% if page.date %}<time datetime="{{ page.date }}">{{ page.date }}</time>{% endif %}
    {% if page.author %}<span class="author">by {{ page.author }}</span>{% endif %}
    {% if page.content %}<span class="reading-time">{{ page.content | reading_time }}</span>{% endif %}
  </header>
  <div class="post-body">{{ page.content | safe }}</div>
  {% if page.tags %}
  <footer>
    <ul class="tags" aria-label="Tags">
      {% for tag in page.tags %}<li><a href="/tags/{{ tag | slugify }}/">{{ tag }}</a></li>{% endfor %}
    </ul>
  </footer>
  {% endif %}
</article>
{% endblock %}
"#,
    )?;

    // templates/tera/index.html
    fs::write(
        root.join("templates/tera/index.html"),
        r#"{% extends "base.html" %}
{% block title %}{{ site.title | default(value="Home") }}{% endblock %}
{% block content %}
<section>{{ page.content | safe }}</section>
{% endblock %}
"#,
    )?;

    // static/css/style.css
    fs::write(
        root.join("static/css/style.css"),
        r#"/* SSG Default Styles */
:root {
  --text: #1a1a2e;
  --bg: #ffffff;
  --accent: #0066cc;
  --muted: #6b7280;
  --border: #e5e7eb;
  --radius: 6px;
}
@media (prefers-color-scheme: dark) {
  :root {
    --text: #e6edf3;
    --bg: #0d1117;
    --accent: #58a6ff;
    --muted: #8b949e;
    --border: #30363d;
  }
}
*, *::before, *::after { box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  color: var(--text);
  background: var(--bg);
  line-height: 1.6;
  max-width: 48rem;
  margin: 0 auto;
  padding: 1rem 1.5rem;
}
a { color: var(--accent); }
nav { display: flex; gap: 1rem; padding: 1rem 0; border-bottom: 1px solid var(--border); }
main { padding: 2rem 0; }
footer { border-top: 1px solid var(--border); padding: 1rem 0; color: var(--muted); font-size: 0.875rem; }
pre { background: #f6f8fa; border: 1px solid var(--border); border-radius: var(--radius); padding: 1em; overflow-x: auto; }
@media (prefers-color-scheme: dark) { pre { background: #161b22; } }
code { font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace; font-size: 0.875em; }
.sr-only { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; }
.admonition { border-left: 4px solid var(--accent); padding: 0.75rem 1rem; margin: 1rem 0; border-radius: var(--radius); }
.admonition-title { font-weight: 600; margin-bottom: 0.25rem; }
.tags { list-style: none; padding: 0; display: flex; gap: 0.5rem; }
.tags li a { background: var(--border); padding: 0.25rem 0.5rem; border-radius: var(--radius); text-decoration: none; font-size: 0.875rem; }
article time, article .author, article .reading-time { color: var(--muted); font-size: 0.875rem; margin-right: 1rem; }
"#,
    )?;

    // data/nav.toml
    fs::write(
        root.join("data/nav.toml"),
        r#"[[links]]
name = "Home"
url = "/"

[[links]]
name = "About"
url = "/about.html"

[[links]]
name = "Blog"
url = "/blog/"
"#,
    )?;

    println!("Created new project: {name}");
    println!("  cd {name}");
    println!("  ssg -f config.toml");

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_scaffold_creates_structure() {
        let dir = tempdir().unwrap();
        let name = "test-site";
        let project_dir = dir.path().join(name);

        scaffold_project_at(name, dir.path()).unwrap();

        assert!(project_dir.join("config.toml").exists());
        assert!(project_dir.join("content/index.md").exists());
        assert!(project_dir.join("content/about.md").exists());
        assert!(project_dir.join("content/blog/first-post.md").exists());
        assert!(project_dir.join("templates/tera/base.html").exists());
        assert!(project_dir.join("templates/tera/page.html").exists());
        assert!(project_dir.join("templates/tera/post.html").exists());
        assert!(project_dir.join("static/css/style.css").exists());
        assert!(project_dir.join("data/nav.toml").exists());

        let config =
            fs::read_to_string(project_dir.join("config.toml")).unwrap();
        assert!(config.contains("test-site"));
    }

    #[test]
    fn test_scaffold_existing_dir_fails() {
        let dir = tempdir().unwrap();
        let name = "existing";
        fs::create_dir(dir.path().join(name)).unwrap();

        let result = scaffold_project_at(name, dir.path());
        assert!(result.is_err());
    }
}
