name: 💾 Format

on:
  push:
    branches:
      - main
      - feat/ssg
  pull_request:
    branches:
      - feat/ssg
  release:
    types: [created]

jobs:
  all:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v2
        with:
          components: clippy
      - uses: actions/checkout@v4
      - name: Check format
        run: cargo fmt --all -- --check --verbose
